### ISSUE TITLE
Do not reload whole schema on each validation call

### ISSUE THREAD

**Issue by kibertoad** [Zooz/api-contract-validator#20]
Currently `apiSchemaBuilder.buildSchemaSync` is called for each and every validation call, which is, unsurprisingly, quite slow and causes timeouts in tests for applications with complex schemas.
Ideally it should be loaded once on plugin initialization and memoized.

**Comment by kobik** [comment]
@kibertoad, are you sure about that? there is a caching of the schema and it shouldn't be reloaded on every validation.

see getSchema function in  https://github.com/Zooz/api-contract-validator/blob/master/lib/helpers/schema-utils.js

**Comment by kibertoad** [comment]
Ah, I see, you are right. Probably the effect that I'm seeing is due to Jest multi-threaded execution, that no caching would help with.
